# Generated by Django 5.2.1 on 2025-05-20 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromptDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_type', models.CharField(help_text='Tipo de prompt (e.g., summary, question, translation)', max_length=50, unique=True)),
                ('prompt_text', models.TextField(help_text="O texto completo do prompt para a IA (e.g., 'Resuma o texto a seguir:')")),
            ],
            options={
                'verbose_name': 'Definição de Prompt',
                'verbose_name_plural': 'Definições de Prompts',
            },
        ),
        migrations.CreateModel(
            name='InputData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='arquivos/')),
                ('text', models.TextField(blank=True, null=True)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('prompt_type', models.ForeignKey(blank=True, help_text='Tipo de prompt para análise (escolha uma definição predefinida)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='input_data_entries', to='casper.promptdefinition')),
            ],
        ),
    ]
