# Generated by Django 5.2.1 on 2025-05-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InputData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='arquivos/')),
                ('text', models.TextField(blank=True, null=True)),
                ('prompt_type', models.CharField(choices=[('summary', 'Summary'), ('question', 'Question'), ('translation', 'Translation'), ('other', 'Other')], default='summary', max_length=50)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
